### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by hlflanagan** [hlflanagan/Registration-Data-Dictionary#2]
John Levine - My only objection is that the name needs to change to something like Registrar Data Dictionary since the only items in it that have anything to do with the DNS are 2.1 and 2.3.

**Comment by hlflanagan** [comment]
George Michaelson - +1 with name change

**Comment by hlflanagan** [comment]
Jianking Yao -   RFC8499 is named with "DNS terminology" while this document is named with "DNS Data Dictionary".
  Just having a quick look at these two names, it seems it is not easy to distinguish between them.

  How about renaming "DNS Data Dictionary" to "DNS Registration Data Dictionary" or [something] else?

**Comment by hlflanagan** [comment]
Peter Mevzek - You could even drop "DNS" from "DNS Registration Data Dictionary". 

First because even today by domain name registrars and registries, EPP/RDAP are used for things that are not related to the DNS at all (ex: contacts).

Second because EPP was created as a generic provisioning protocol that
technically could handle things completely unrelated to domain names, even if it is its only major public generic use.

**Comment by hlflanagan** [comment]
George Michaelson - I agree with Jiankang that the similarity to the DNS terminology draft is unfortunate. I would stick to registration, distinct from DNS.
REGEXT is about more than DNS registry, so the ontology here has to be about more than DNS too.

**Comment by dnsguru** [comment]
+1 on dropping DNS from title.

**Comment by hlflanagan** [comment]
Title has been updated.
